version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=vehicle_maintenance
      - DB_USER=vehicle_app
      - DB_PASSWORD=T3c#Crunc#
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=T3c#Crunc#
      - MYSQL_DATABASE=vehicle_maintenance
      - MYSQL_USER=vehicle_app
      - MYSQL_PASSWORD=T3c#Crunc#
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: